# THIS IS A DUMMY FILE
eye_on_hand: true
parent: b_bot_ee_link
child: calibrated_b_bot_inside_camera_color_optical_frame
transform: {x: 0.01, y: -0.0, z: 0.09, qx: -0.43030, qy: 0.4307, qz: -0.56108, qw: 0.56075}
calibration_date: This is a dummy calibration file
